name: Build-Caddy
on:
  schedule:
    - cron: "30 5 * * 2"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build caddy & Push to repo
      run: |
        bash build.sh
