name: Build

on:
  schedule:
    - cron: "15 6 1 */2 *"
  release:
    types: [created]

jobs:

  Build-Release-Caddy:
    name: Release Caddy Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Print Go version and environment
      id: vars
      run: |
          printf "Using go at: $(which go)\n"
          printf "Go version: $(go version)\n"
          printf "\n\nGo environment:\n\n"
          go env
          printf "\n\nSystem environment:\n\n"
          env
    - name: Install xcaddy and Build caddy
      run:
        bash build.sh
    - name: Release
      uses: wangyoucao577/go-release-action@v1.29
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "test-binary"
        extra_files: caddy.json Caddyfile caddy.service
